version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=mi_basededatos
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=mi_basededatos
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: